### ISSUE TITLE
Is there any new thing in the future?

### ISSUE THREAD

**Issue by xindoo** [google/eng-practices#21]
This project didn't add new content in the past 6 months, and could I know is there any new thing or an updated plan in the future.

**Comment by ninachen** [comment]
At this time, no, nothing is planned for major new content for this repo. I also expect people's availability to work on this to be more limited while everyone is working from home, since what limited productivity people have is probably being spent on their main projects.

As for the existing content, the copybara service automatically pulls in changes whenever we make changes to the internal version.

* * *

That said, I'm happy to plug that the [_Software Engineering at Google_ O'Reilly book](https://www.oreilly.com/library/view/software-engineering-at/9781492082781/) is available digitally now or in paperback tomorrow (2020-03-17), which covers a whole lot more of Google's engineering practices.

I suspect that whatever specific content you are looking for might already be covered in the book. 😃
